name: Word List Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up CMake & Compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-14
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100

      - name: Configure and Compile C++ Project
        run: |
          cmake -B out/build -DCMAKE_BUILD_TYPE=Release
          cmake --build out/build

      - name: Run Executable in Dist Folder to Build Word List
        run: |
          cd out/build/dist/
          chmod +x ./word_list_builder
          ./word_list_builder
          cd ../../..

      - name: Commit and Push Clean Asset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          mkdir -p data/

          cp out/build/dist/word_list.json data/word_list.json
          
          git add data/word_list.json || true
          git commit -m "Auto-update word list [skip ci]" || true
          git push
